name: vidcutter
version: 6.0.5
type: app
base: core20
architectures:
    - amd64
summary: the simplest + fastest media cutter and joiner
description: |
    A modern, simple to use, constantly evolving and 
    hella fast MEDIA CUTTER + JOINER w/ frame-accurate
    SmartCut technology + Qt5, libmpv, FFmpeg and
    MediaInfo powering the backend.
icon: data/icons/hicolor/512x512/apps/com.ozmartians.VidCutter.png

grade: stable
confinement: strict

apps:
    vidcutter:
        command: bin/desktop-launch $SNAP/bin/vidcutter
        plugs: [unity7, x11, wayland, desktop, home, pulseaudio, gsettings, opengl, mount-observe, network, network-bind, network-manager]
        desktop: share/applications/com.ozmartians.VidCutter.desktop

parts:
    prepare:
        plugin: nil
        build-packages:
            - software-properties-common
        override-build: |
            add-apt-repository ppa:ozmartian/apps -y
            apt update
            apt upgrade -yy
        prime: [-*]

    desktop-qt5:
        plugin: nil
        after: [prepare]
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libgdk-pixbuf2.0-0
            - locales-all
            - xdg-user-dirs
            - mesa-vdpau-drivers
            - libglu1-mesa
            - libdb5.3
            - libgtk2.0-0

    vidcutter:
        plugin: nil
        after: [prepare, desktop-qt5]
        stage-packages:
            - vidcutter
