name: vidcutter
version: 5.5.0
type: app
architectures: [amd64, i386]
summary: the simplest + fastest video cutter and joiner
description: |
    A modern, simple to use, constantly evolving and 
    hella fast MEDIA CUTTER + JOINER w/ frame-accurate
    SmartCut technology + Qt5, libmpv, FFmpeg and
    MediaInfo powering the backend.
icon: vidcutter.png

grade: devel
confinement: devmode

apps:

    vidcutter:
        command: desktop-launch vidcutter
        plugs: [desktop, home, pulseaudio, alsa, opengl]
        desktop: usr/share/applications/com.ozmartians.vidcutter.desktop

parts:
    vidcutter:
        plugin: python
        source: https://github.com/ozmartian/vidcutter.git
        source-type: git
        source-depth: 1 
        process-dependency-links: false
        after: [desktop-qt5]
        build-packages:
            - python3-dev
            - python3-setuptools
            - libmpv-dev
        stage-packages:
            - python3-pyqt5
            - python3-pyqt5.qtopengl
            - python3-pyqt5.qtx11extras
            - python3-opengl
            - libmpv1
            - ffmpeg
            - mediainfo

    desktop-qt5:
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libqt5gui5
            - libgdk-pixbuf2.0-0
            - libqt5svg5
            - locales-all
            - xdg-user-dirs
