name: vidcutter
version: 6.0.5
type: app
base: core20
architectures:
    - amd64
summary: the simplest + fastest media cutter and joiner
description: |
    A modern, simple to use, constantly evolving and 
    hella fast MEDIA CUTTER + JOINER w/ frame-accurate
    SmartCut technology + Qt5, libmpv, FFmpeg and
    MediaInfo powering the backend.
icon: data/icons/hicolor/512x512/apps/com.ozmartians.VidCutter.png

grade: stable
confinement: strict

apps:
    vidcutter:
        command: bin/desktop-launch $SNAP/bin/vidcutter
        plugs: [unity7, x11, wayland, desktop, home, audio-playback, gsettings, opengl, mount-observe, network, network-bind, network-manager]
        desktop: share/applications/com.ozmartians.VidCutter.desktop

parts:
    prepare:
        plugin: nil
        build-packages:
            - software-properties-common
        prime: [-*]

    desktop-qt5:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: qt
        plugin: make
        after: [prepare]
        make-parameters: ["FLAVOR=qt5"]
        build-packages:
            - build-essential
            - qtbase5-dev
            - dpkg-dev
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libqt5gui5
            - libgdk-pixbuf2.0-0
            - libqt5svg5 # for loading icon themes which are svg
            - try: [appmenu-qt5] # not available on core18
            - locales-all
            - xdg-user-dirs
            - fcitx-frontend-qt5
            - libgtk2.0-0

    vidcutter:
        plugin: python
        source: .
        after: [prepare, desktop-qt5]
        build-packages:
            - python3-dev
            - python3-setuptools
            - libmpv-dev
            - sip-dev
        stage-packages:
            - libmpv1
            - ffmpeg
            - mediainfo
        python-packages:
            # - pyqt5==5.14.1
            - pyqt5==5.10.1
            - pyopengl
            - simplejson
