name: vidcutter
version: 6.0.0
type: app
architectures:
    - amd64
summary: the simplest + fastest media cutter and joiner
description: |
    A modern, simple to use, constantly evolving and 
    hella fast MEDIA CUTTER + JOINER w/ frame-accurate
    SmartCut technology + Qt5, libmpv, FFmpeg and
    MediaInfo powering the backend.
icon: data/icons/hicolor/512x512/apps/com.ozmartians.VidCutter.png

grade: stable
confinement: strict

apps:
    vidcutter:
        command: desktop-launch vidcutter
        plugs: [unity7, x11, wayland, desktop, home, pulseaudio, gsettings, opengl, mount-observe, network, network-bind, network-manager]
        desktop: share/applications/com.ozmartians.VidCutter.desktop

parts:
    prepare:
        plugin: nil
        build-packages:
            - software-properties-common
        override-build: |
            add-apt-repository ppa:mc3man/mpv-tests -y
            add-apt-repository ppa:jonathonf/ffmpeg-3 -y
            apt update
            apt upgrade -yy
        prime: [-*]

    desktop-qt5:
        after: [prepare]
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libgdk-pixbuf2.0-0
            - locales-all
            - xdg-user-dirs
            - mesa-vdpau-drivers
            - libglu1-mesa
            - libdb5.3

    vidcutter:
        plugin: python
        python-version: python3
        after: [prepare, desktop-qt5]
        build-packages:
            - python3-dev
            - python3-setuptools
            - libmpv-dev
        stage-packages:
            - libmpv1
            - ffmpeg
            - mediainfo
        python-packages:
            - pyqt5==5.10.1
            - pyopengl
            - simplejson
        install: |
            sed -i 's|Icon=.*|Icon=${SNAP}/share/icons/hicolor/512x512/apps/com.ozmartians.VidCutter.png|g' ${SNAPCRAFT_PART_INSTALL}/share/applications/com.ozmartians.VidCutter.desktop
            rm ${SNAPCRAFT_PART_INSTALL}/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5
